services:
  traceroutemap:
    image: cantanope/traceroutemap_image:latest
    container_name: traceroutemap_container
    ports:
      - "8002:80"
    restart: unless-stopped
    networks:
      - default